<?php
/**
 * Daily Impact Devotional - Database Configuration
 * 
 * This file is auto-generated by install.php.
 * Edit it manually only if you know what you're doing.
 */

// ─── Database Credentials (edit these or use install.php) ───────────────────
$db_host = 'localhost';
$db_name = 'dailyimpact_devotional';
$db_user = 'root';
$db_pass = '';

// ─── File Upload Directory (relative to project root) ───────────────────────
// cPanel deployment uses /upload with dedicated subfolders.
define('UPLOADS_DIR', __DIR__ . '/../../upload');
define('HEADERS_DIR', UPLOADS_DIR . '/headers');
// NOTE: the actual folder created & used for devotional DOCX files is
// 'upload/devotionals' (plural) — kept consistent everywhere (upload.php,
// health.php, install.php). The old 'devotional' (singular) folder is unused.
define('DEVOTIONALS_DIR', UPLOADS_DIR . '/devotionals');

// ─── JSON-only error handling ───────────────────────────────────────────────
// The API must never leak PHP warnings or fatal HTML error pages. Suppress
// inline output, then convert uncaught exceptions and fatal errors into JSON.
ini_set('display_errors', '0');
error_reporting(E_ALL);

set_exception_handler(function (Throwable $e): void {
    http_response_code(500);
    if (!headers_sent()) {
        header('Content-Type: application/json; charset=utf-8');
    }
    $msg = $e->getMessage();
    // Same contract as jsonError(): {success:false, message, error}
    echo json_encode(['success' => false, 'message' => $msg, 'error' => $msg]);
    exit;
});

register_shutdown_function(function (): void {
    $err = error_get_last();
    if ($err && in_array($err['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR], true)) {
        http_response_code(500);
        if (!headers_sent()) {
            header('Content-Type: application/json; charset=utf-8');
        }
        $msg = 'Server error: ' . $err['message'];
        // Same contract as jsonError(): {success:false, message, error}
        echo json_encode(['success' => false, 'message' => $msg, 'error' => $msg]);
    }
});

// ─── PDO Connection ─────────────────────────────────────────────────────────
try {
    $pdo = new PDO(
        "mysql:host=$db_host;dbname=$db_name;charset=utf8mb4",
        $db_user,
        $db_pass,
        [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
        ]
    );
} catch (PDOException $e) {
    // Don't exit here — let the calling endpoint decide how to respond.
    // If config is loaded before DB is ready, all functions below still need to exist.
    $pdo = null;
    $GLOBALS['db_error'] = $e->getMessage();
}

// ─── CORS Headers ───────────────────────────────────────────────────────────
function sendCorsHeaders(): void {
    // CORS: only reflect an Origin that matches this site (or local dev), never
    // a wildcard — a wildcard would let ANY website read API responses and ride
    // cookie-authenticated requests. Same-origin requests (the normal case) are
    // unaffected.
    $origin = (string)($_SERVER['HTTP_ORIGIN'] ?? '');
    $host   = (string)($_SERVER['HTTP_HOST'] ?? '');
    if ($origin !== '') {
        // Vary on Origin whenever an Origin is present (cache correctness).
        header('Vary: Origin');
        $oHost = (string)parse_url($origin, PHP_URL_HOST);
        $hostNoPort = preg_replace('/:\d+$/', '', $host);
        // The localhost carve-out is dev convenience only; it is safe because
        // the session cookie is SameSite=Lax (withheld on cross-site fetch).
        // If a cookie ever becomes SameSite=None or a Bearer token is added,
        // remove the $isLocal allowance.
        $isLocal = (bool)preg_match('/^(localhost|127\.0\.0\.1|\[::1\])$/i', $oHost);
        if ($oHost !== '' && ($isLocal || ($hostNoPort !== null && strcasecmp($oHost, $hostNoPort) === 0))) {
            header('Access-Control-Allow-Origin: ' . $origin);
            header('Access-Control-Allow-Credentials: true');
        }
    }
    header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type, Authorization');
    header('Content-Type: application/json; charset=utf-8');

    // Hardening headers — clickjacking, MIME sniffing, referrer leakage.
    header('X-Frame-Options: SAMEORIGIN');
    header('X-Content-Type-Options: nosniff');
    header('Referrer-Policy: strict-origin-when-cross-origin');
    header('Permissions-Policy: geolocation=(), microphone=(), camera=(), payment=()');

    // API responses must never be cached by the browser/proxy — otherwise a
    // stale GET /devotionals.php response can resurrect a row the admin just
    // deleted ("deleted it, then it came back").
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    header('Pragma: no-cache');

    if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
        http_response_code(200);
        exit;
    }
}

// ─── Webhook Flood Guard ────────────────────────────────────────────────────
// Payment gateways retry webhooks; forged/rogue clients should be throttled.
// Signature verification (webhook-payment.php) is the PRIMARY control — this
// guard is defense-in-depth and best-effort (never blocks on guard errors).
function ensureWebhookGuard(): void {
    global $pdo;
    if (!$pdo instanceof PDO) {
        return;
    }
    static $checked = false;
    if ($checked) {
        return;
    }
    $checked = true;
    try {
        $pdo->exec("CREATE TABLE IF NOT EXISTS webhook_events (
            id INT AUTO_INCREMENT PRIMARY KEY,
            ip_address VARCHAR(45) NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_wh_ip_time (ip_address, created_at)
        ) ENGINE=InnoDB");
    } catch (Throwable $e) {
        // Non-fatal — the guard is best-effort.
    }
}

function webhookAllowed(string $ip, int $maxPerMinute = 15): bool {
    global $pdo;
    if ($ip === '' || !$pdo instanceof PDO) {
        return true;
    }
    try {
        // Prune old rows, then count this IP's requests in the last minute.
        $pdo->exec("DELETE FROM webhook_events WHERE created_at < NOW() - INTERVAL 10 MINUTE");
        $stmt = $pdo->prepare(
            "SELECT COUNT(*) FROM webhook_events
             WHERE ip_address = ? AND created_at >= NOW() - INTERVAL 1 MINUTE"
        );
        $stmt->execute([$ip]);
        if ((int)$stmt->fetchColumn() >= $maxPerMinute) {
            return false;
        }
        $ins = $pdo->prepare("INSERT INTO webhook_events (ip_address) VALUES (?)");
        $ins->execute([$ip]);
        return true;
    } catch (Throwable $e) {
        return true; // Fail-open only on guard errors — signature check still protects.
    }
}

// Resolve the effective HTTP method. Some shared hosts (cPanel/ModSecurity)
// block the DELETE/PUT verbs outright, so the frontend falls back to sending
// POST with ?_method=DELETE (or ?_method=PUT). All DELETE/PUT handlers require
// an admin session, so honoring this override is safe.
function httpMethod(): string {
    $m = strtoupper($_SERVER['REQUEST_METHOD'] ?? 'GET');
    if ($m === 'POST') {
        $override = $_GET['_method'] ?? '';
        if (is_string($override) && in_array(strtoupper($override), ['PUT', 'DELETE'], true)) {
            return strtoupper($override);
        }
    }
    return $m;
}

// ─── JSON Helpers ───────────────────────────────────────────────────────────
function jsonInput(): array {
    $raw = file_get_contents('php://input');
    if (empty($raw)) {
        return [];
    }
    $data = json_decode($raw, true);
    if (!is_array($data)) {
        jsonError('Invalid JSON body', 400);
    }
    return $data;
}

function jsonResponse(mixed $data, int $code = 200): void {
    http_response_code($code);
    // JSON_INVALID_UTF8_SUBSTITUTE: imported DOCX content can contain invalid
    // UTF-8 bytes; without this flag json_encode() returns false and the whole
    // response goes blank — which previously made devotionals "disappear" from
    // the admin dashboard (and homepage) after reload while DB rows remained.
    echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_INVALID_UTF8_SUBSTITUTE);
    exit;
}

// ─── UTF-8 Sanitizer ─────────────────────────────────────────────────────────
// Strips invalid UTF-8 byte sequences from imported text (DOCX parsing, manual
// pastes) so JSON responses and json_encode() never fail on bad bytes.
function utf8Safe(mixed $value): mixed {
    if (is_array($value)) {
        foreach ($value as $k => $v) {
            $value[$k] = utf8Safe($v);
        }
        return $value;
    }
    if (is_string($value)) {
        // Fast path: the overwhelming majority of content is already valid
        // UTF-8. A single /u regex check is far cheaper than iconv() per field,
        // so we only pay the iconv cost for genuinely broken strings (imported
        // DOCX content). This makes the GET /devotionals response dramatically
        // faster on shared hosting (hundreds of rows x many fields).
        if (preg_match('//u', $value)) {
            return $value;
        }
        // iconv //IGNORE drops invalid sequences; fall back to regex scrub.
        $clean = @iconv('UTF-8', 'UTF-8//IGNORE', $value);
        if ($clean !== false) {
            return $clean;
        }
        return preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F]/u', '', $value) ?? $value;
    }
    return $value;
}

function jsonError(string $message, int $code = 400): void {
    // Documented contract: {success: false, message: ...}.
    // 'error' is kept for backward compatibility with older clients.
    jsonResponse([
        'success' => false,
        'message' => $message,
        'error'   => $message,
    ], $code);
}

// ─── Auth Helper ────────────────────────────────────────────────────────────
function requireAdmin(): void {
    // Use secureSession() for consistent session handling (configure, timeout check, IP binding)
    if (!secureSession()) {
        jsonError('Unauthorized. Please log in first.', 401);
    }
}

// ─── Roles & Permissions ────────────────────────────────────────────────────
// The Administrator can restrict which dashboard sections each staff role
// (Assistant Editor / Guest Writer) can see. Permissions are stored as JSON in
// the settings table under the key 'role_permissions'. The Administrator role
// ALWAYS has full access and cannot be restricted server-side.

/** All dashboard sections that can be granted per role (key => display name). */
function roleSections(): array {
    return [
        'overview'             => 'Overview Console',
        'add-devotional'       => 'Add Devotional',
        'manage-devotionals'   => 'List Devotionals',
        'import-devotional'    => 'Import Devotional',
        'header-images'        => 'Header Images',
        'user-management'      => 'User Management',
        'telegram-integration' => 'Telegram Channel',
        'foreword'             => 'Foreword',
        'payments'             => 'Payments & Donations',
        'analytics'            => 'Website Analytics',
        'settings'             => 'Settings',
    ];
}

/** Default permission matrix used when nothing has been saved yet. */
function defaultRolePermissions(): array {
    $all = array_keys(roleSections());
    return [
        'Administrator'    => $all,
        'Assistant Editor' => ['overview', 'add-devotional', 'manage-devotionals', 'import-devotional', 'header-images', 'foreword', 'telegram-integration', 'analytics'],
        'Guest Writer'     => ['overview', 'add-devotional', 'manage-devotionals', 'import-devotional'],
    ];
}

/** Load saved role permissions, merged over the defaults (missing roles/sections keep defaults). */
function getRolePermissions(): array {
    requireDb();
    $defaults = defaultRolePermissions();
    $sections = array_keys(roleSections());
    try {
        $saved = json_decode((string)getSetting('role_permissions', ''), true);
    } catch (Throwable $e) {
        // Settings table may not exist yet on a partially-migrated DB — fall
        // back to the defaults rather than surfacing a 500.
        return $defaults;
    }
    if (!is_array($saved)) {
        return $defaults;
    }
    $result = [];
    foreach ($defaults as $role => $allowed) {
        $list = $saved[$role] ?? $allowed;
        if (!is_array($list)) {
            $list = $allowed;
        }
        // Only keep known sections; Administrator is always unrestricted.
        if ($role === 'Administrator') {
            $result[$role] = $sections;
        } else {
            $result[$role] = array_values(array_intersect($list, $sections));
        }
    }
    return $result;
}

/** Normalize a DB role value to the display string used across the app. */
function normalizeRole(string $role): string {
    $r = strtolower(trim($role));
    if ($r === 'admin') return 'Administrator';
    if ($r === 'editor') return 'Assistant Editor';
    if ($r === 'guest') return 'Guest Writer';
    return $role;
}

/** The normalized role of the currently logged-in admin ('' when anonymous). */
function currentAdminRole(): string {
    if (empty($_SESSION['admin_role'])) {
        return '';
    }
    return normalizeRole((string)$_SESSION['admin_role']);
}

/** Whether the current admin role may see a given dashboard section. */
function canAccessSection(string $section): bool {
    $role = currentAdminRole();
    if ($role === 'Administrator') {
        return true;
    }
    if ($role === '') {
        return false;
    }
    $perms = getRolePermissions();
    return in_array($section, $perms[$role] ?? [], true);
}

/** Can the current role see ANY of the given sections? (e.g. devotional writes.) */
function canAccessAnySection(array $sections): bool {
    foreach ($sections as $s) {
        if (canAccessSection($s)) {
            return true;
        }
    }
    return false;
}

/** requireAdmin() + section permission gate (403 when the role lacks access). */
function requireSection(string $section): void {
    requireAdmin();
    if (!canAccessSection($section)) {
        jsonError('Access denied: your role cannot view this section.', 403);
    }
}

/** requireAdmin() + ANY-of gate — used where one endpoint backs several tabs. */
function requireAnySection(array $sections): void {
    requireAdmin();
    if (!canAccessAnySection($sections)) {
        jsonError('Access denied: your role cannot perform this action.', 403);
    }
}

// ─── ID Generator ───────────────────────────────────────────────────────────
// Standard UUID v4 (36 chars) — fits the VARCHAR(36) id columns.
// (The old format produced 48 chars, which MySQL strict mode rejects.)
function generateId(): string {
    $data = random_bytes(16);
    $data[6] = chr((ord($data[6]) & 0x0f) | 0x40); // version 4
    $data[8] = chr((ord($data[8]) & 0x3f) | 0x80); // variant
    return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
}

// ─── Settings Helper ────────────────────────────────────────────────────────
function requireDb(): void {
    global $pdo;
    if (!$pdo instanceof PDO) {
        throw new RuntimeException('Database connection failed. Check config/db.php credentials and database availability.');
    }
}

function getSettings(): array {
    requireDb();
    global $pdo;
    $stmt = $pdo->query("SELECT setting_key, setting_value FROM settings");
    $settings = [];
    while ($row = $stmt->fetch()) {
        $settings[$row['setting_key']] = $row['setting_value'];
    }
    // Secrets are stored encrypted — decrypt for all internal consumers.
    return decryptSettings($settings);
}

function getSetting(string $key, mixed $default = null): mixed {
    requireDb();
    global $pdo;
    $stmt = $pdo->prepare("SELECT setting_value FROM settings WHERE setting_key = ?");
    $stmt->execute([$key]);
    $val = $stmt->fetchColumn();
    if ($val === false) {
        return $default;
    }
    return isSecretSettingKey($key) ? decryptSecret($val) : $val;
}

function setSetting(string $key, string $value): void {
    requireDb();
    global $pdo;
    $stmt = $pdo->prepare(
        "INSERT INTO settings (setting_key, setting_value) VALUES (?, ?)
         ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)"
    );
    $stmt->execute([$key, $value]);
}

// ─── Secret Encryption (AES-256-CBC) ───────────────────────────────────────
// Credentials (Telegram bot token, channel id, SMTP pass, payment secrets,
// webhook secret) are encrypted at rest so a DB dump alone can't leak them.
// The encryption key lives in a file OUTSIDE the web root (../secret.key,
// one level up from config/ — not web-accessible). getSettings()/getSetting()
// decrypt transparently, so all existing consumers keep working unchanged.

/** Setting keys whose values are stored encrypted. */
function secretSettingKeys(): array {
    return [
        'telegram_bot_token',
        'telegram_channel_id',
        'resend_api_key',
        'smtp_pass',
        'paystack_secret_key',
        'flutterwave_secret_key',
        'flutterwave_encryption_key',
        'webhook_secret',
    ];
}

function isSecretSettingKey(string $key): bool {
    return in_array($key, secretSettingKeys(), true);
}

/**
 * Load (or lazily create) the site's encryption key.
 *
 * The key is stored in config/secret.key.php — a PHP file that just returns
 * the key string. A direct web request to it executes PHP and outputs nothing
 * (the file is also denied by config/.htaccess), so the key can never be
 * downloaded as plain text even though config/ lives under public_html.
 *
 * If the file can't be written (e.g. first request on a locked-down host),
 * we fall back to a per-install derived key so nothing breaks — but we
 * always attempt to persist so subsequent requests use the stable file key.
 */
function encryptionKey(): string {
    static $key = null;
    if ($key !== null) {
        return $key;
    }

    $keyFile = __DIR__ . '/secret.key.php';
    if (is_file($keyFile)) {
        $stored = include $keyFile; // returns the key string
        if (is_string($stored) && strlen($stored) >= 32) {
            $key = $stored;
            return $key;
        }
    }

    // Generate a fresh 32-byte key (hex = 64 chars) and persist it as a PHP
    // file (executes to an empty page if ever hit directly via the web).
    // Exclusive-create ('x' mode): concurrent first requests can't each write
    // a different key — only ONE request wins the race; the losers re-read the
    // winner's file below. This keeps every request on the same persisted key.
    $generated = bin2hex(random_bytes(32));
    $phpContent = "<?php\n" .
        "// Auto-generated encryption key for Daily Impact Devotional.\n" .
        "// DO NOT EDIT OR DELETE — deleting it makes stored secrets undecryptable.\n" .
        "return '" . $generated . "';\n";
    $handle = @fopen($keyFile, 'x');
    if ($handle !== false) {
        fwrite($handle, $phpContent);
        fclose($handle);
        @chmod($keyFile, 0600);
        $key = $generated;
        return $key;
    }

    // Another request created the file first (fopen 'x' failed) — use it.
    if (is_file($keyFile)) {
        $stored = include $keyFile;
        if (is_string($stored) && strlen($stored) >= 32) {
            $key = $stored;
            return $key;
        }
    }

    // Fallback: derive a stable per-install key from the DB config. Only used
    // if the key file could not be created (should be rare on real hosts).
    global $db_host, $db_name, $db_user, $db_pass;
    $key = hash('sha256',
        ($db_host ?? 'localhost') . '|' . ($db_name ?? '') . '|' .
        ($db_user ?? '') . '|' . ($db_pass ?? '') . '|dailyimpact-secret'
    );
    return $key;
}

/** Encrypt a plaintext secret for storage. Empty stays empty. */
function encryptSecret(string $plain): string {
    if ($plain === '') {
        return '';
    }
    // Already encrypted (double-save safety) — return as-is.
    if (str_starts_with($plain, 'enc:v1:')) {
        return $plain;
    }
    $key = hash('sha256', encryptionKey(), true); // 32 raw bytes
    $iv  = random_bytes(16);
    $cipher = openssl_encrypt($plain, 'AES-256-CBC', $key, OPENSSL_RAW_DATA, $iv);
    if ($cipher === false) {
        // openssl missing — never silently downgrade. Mark the value explicitly
        // and log loudly so the ops team knows secrets are NOT encrypted at rest.
        error_log('CRYPTO WARNING: openssl_encrypt failed — storing secret with plain: marker (not encrypted at rest).');
        return 'plain:' . $plain;
    }
    return 'enc:v1:' . base64_encode($iv . $cipher);
}

/** Decrypt a stored secret. Handles plaintext (legacy), explicit plain: markers and empty values. */
function decryptSecret(string $stored): string {
    if ($stored === '' || !str_starts_with($stored, 'enc:v1:')) {
        // Explicit plaintext marker (crypto downgrade) — strip the prefix.
        if (str_starts_with($stored, 'plain:')) {
            return substr($stored, 6);
        }
        return $stored; // empty or legacy plaintext
    }
    $raw = base64_decode(substr($stored, 7), true);
    if ($raw === false || strlen($raw) <= 16) {
        return '';
    }
    $iv     = substr($raw, 0, 16);
    $cipher = substr($raw, 16);
    $key    = hash('sha256', encryptionKey(), true);
    $plain  = openssl_decrypt($cipher, 'AES-256-CBC', $key, OPENSSL_RAW_DATA, $iv);
    return $plain === false ? '' : $plain;
}

/**
 * Store a setting, transparently encrypting secret keys at rest.
 * Empty values are stored empty (which clears the credential).
 */
function setSecretSetting(string $key, string $value): void {
    if ($value !== '' && isSecretSettingKey($key)) {
        $value = encryptSecret($value);
    }
    setSetting($key, $value);
}

/**
 * Massage a settings array for internal consumers: decrypt secret keys so
 * telegram.php, send-mail.php, payments etc. keep working unchanged.
 */
function decryptSettings(array $settings): array {
    foreach (secretSettingKeys() as $k) {
        if (isset($settings[$k])) {
            $settings[$k] = decryptSecret($settings[$k]);
        }
    }
    return $settings;
}

// ─── Month/Folder Helpers ───────────────────────────────────────────────────
function getMonthFolder(string $month, int $year): string {
    $month = strtolower(trim($month));
    return "{$month}_{$year}";
}

function ensureUploadDir(string $subpath): string {
    $dir = UPLOADS_DIR . '/' . ltrim($subpath, '/');
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    return $dir;
}

function getClientIp(): string {
    if (!empty($_SERVER['HTTP_CF_CONNECTING_IP'])) {
        return trim((string)$_SERVER['HTTP_CF_CONNECTING_IP']);
    }
    if (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
        $parts = array_map('trim', explode(',', (string)$_SERVER['HTTP_X_FORWARDED_FOR']));
        if (!empty($parts[0])) {
            return $parts[0];
        }
    }
    return $_SERVER['REMOTE_ADDR'] ?? 'unknown';
}

function ipVersion(string $ip): int {
    return filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) ? 6 : 4;
}

function subnetForIp(string $ip, int $maskV4 = 24, int $maskV6 = 64): string {
    if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
        $bin = inet_pton($ip);
        if ($bin === false) {
            return $ip;
        }
        $maskBytes = intdiv($maskV6, 8);
        $remainder = $maskV6 % 8;
        $masked = substr($bin, 0, $maskBytes);
        if ($remainder > 0) {
            $byte = ord(substr($bin, $maskBytes, 1));
            $byte = $byte & (0xFF << (8 - $remainder));
            $masked .= chr($byte);
            $maskBytes++;
        }
        $masked = str_pad($masked, 16, "\0");
        return inet_ntop($masked) . "/{$maskV6}";
    }

    $octets = explode('.', $ip);
    if (count($octets) !== 4) {
        return $ip;
    }
    return sprintf('%d.%d.%d.0/%d', (int)$octets[0], (int)$octets[1], (int)$octets[2], $maskV4);
}

function ipRangeForSubnet(string $cidr): array {
    if (str_contains($cidr, '/')) {
        [$ip, $prefix] = explode('/', $cidr, 2);
        $prefix = (int)$prefix;
    } else {
        $ip = $cidr;
        $prefix = filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) ? 64 : 24;
    }

    if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
        $bin = inet_pton($ip);
        if ($bin === false) {
            return [$cidr, $cidr];
        }
        $start = $bin;
        $end = $bin;
        $fullBytes = intdiv($prefix, 8);
        $remainder = $prefix % 8;
        for ($i = $fullBytes; $i < 16; $i++) {
            $start[$i] = "\0";
            $end[$i] = "\xff";
        }
        if ($remainder > 0 && $fullBytes < 16) {
            $mask = 0xFF << (8 - $remainder);
            $start[$fullBytes] = chr(ord($start[$fullBytes]) & $mask);
            $end[$fullBytes] = chr(ord($end[$fullBytes]) | (0xFF ^ $mask));
        }
        return [inet_ntop($start), inet_ntop($end)];
    }

    $long = ip2long($ip);
    if ($long === false) {
        return [$cidr, $cidr];
    }
    $mask = -1 << (32 - $prefix);
    $start = $long & $mask;
    $end = $start | (~$mask & 0xFFFFFFFF);
    return [long2ip($start), long2ip($end)];
}

function normalizeSubnet(string $ip): string {
    return subnetForIp($ip);
}

/**
 * Numeric IP range check (IPv4 or IPv6).
 *
 * ban_start/ban_end are stored as VARCHAR strings (e.g. "105.112.50.0" /
 * "105.112.50.255"). Comparing them with string operators in SQL is WRONG:
 * "105.112.50.37" > "105.112.50.255" lexically ('3' > '2'), so a /24 ban
 * silently never matched most IPs — the auto-IP-ban appeared to do nothing.
 * We therefore fetch candidate bans and compare the packed binary form here.
 */
function isIpInRange(string $ip, string $start, string $end): bool {
    if (str_contains($ip, ':') || str_contains($start, ':')) {
        $bin = @inet_pton($ip);
        $s   = @inet_pton($start);
        $e   = @inet_pton($end);
        if ($bin === false || $s === false || $e === false) return false;
        return strcmp($bin, $s) >= 0 && strcmp($bin, $e) <= 0;
    }
    $l = ip2long($ip);
    $s = ip2long($start);
    $e = ip2long($end);
    if ($l === false || $s === false || $e === false) return false;
    return $l >= $s && $l <= $e;
}

/**
 * Idempotently create the ip_bans table if it is missing.
 *
 * Older deployments (pre-ip_bans database.sql) have no ban table, which made
 * getBanForIp()/recordIpBan() throw an SQL error on EVERY login attempt — the
 * countdown never advanced and no ban was ever recorded. Self-healing here
 * means a stale database starts enforcing bans immediately, no re-install.
 */
function ensureBanTable(): void {
    global $pdo;
    if (!$pdo instanceof PDO) {
        return;
    }
    static $checked = false;
    if ($checked) {
        return;
    }
    $checked = true;
    try {
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS ip_bans (
                id VARCHAR(36) PRIMARY KEY,
                ip_address VARCHAR(45) NOT NULL,
                ip_version TINYINT(1) NOT NULL DEFAULT 4,
                cidr VARCHAR(80) NOT NULL,
                ban_start VARCHAR(80) NOT NULL,
                ban_end VARCHAR(80) NOT NULL,
                reason VARCHAR(255) NOT NULL,
                source VARCHAR(50) DEFAULT 'admin-login',
                email VARCHAR(255) DEFAULT '',
                failed_attempts INT DEFAULT 0,
                active TINYINT(1) DEFAULT 1,
                whitelisted TINYINT(1) NOT NULL DEFAULT 0,
                unbanned_at TIMESTAMP NULL,
                unbanned_by VARCHAR(255) DEFAULT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE KEY uk_cidr (cidr),
                INDEX idx_active (active),
                INDEX idx_ip_address (ip_address)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
        );
        // Add the whitelisted column on existing installs (idempotent).
        $bCols = $pdo->query("SHOW COLUMNS FROM ip_bans")->fetchAll(PDO::FETCH_COLUMN);
        if (!in_array('whitelisted', $bCols, true)) {
            $pdo->exec("ALTER TABLE ip_bans ADD COLUMN whitelisted TINYINT(1) NOT NULL DEFAULT 0 AFTER active");
        }

        // ── Schema self-heal (ban → unban → re-ban → unban) ───────────────
        // The original schema used UNIQUE KEY uk_cidr_active (cidr, active),
        // which allowed a SECOND row per subnet after an unban: the old row
        // holds (cidr, 0), a re-ban inserts a fresh (cidr, 1) row, and the
        // next unban tries to flip that row to (cidr, 0) — colliding with the
        // still-present inactive row. MySQL rejects the UPDATE with a
        // duplicate-key error, so the dashboard showed "Failed to remove IP
        // ban" forever after the first ban→unban→re-ban cycle.
        //
        // Fix: keep ONE row per subnet (UNIQUE KEY uk_cidr) and toggle active.
        // re-ban re-activates the same row via ON DUPLICATE KEY UPDATE, so
        // unban never collides. Migrate existing tables idempotently.
        $dbName = (string)$pdo->query("SELECT DATABASE()")->fetchColumn();
        $idxStmt = $pdo->prepare(
            "SELECT COUNT(*) FROM information_schema.STATISTICS
             WHERE TABLE_SCHEMA = ? AND TABLE_NAME = 'ip_bans' AND INDEX_NAME = 'uk_cidr_active'"
        );
        $idxStmt->execute([$dbName]);
        if ((int)$idxStmt->fetchColumn() > 0) {
            // Collapse duplicates: prefer the newest ACTIVE ban per subnet,
            // drop stale inactive rows and older duplicates.
            $pdo->exec(
                "DELETE b FROM ip_bans b
                 INNER JOIN ip_bans k
                   ON k.cidr = b.cidr
                  AND (k.active > b.active OR (k.active = b.active AND k.created_at > b.created_at))"
            );
            $pdo->exec("ALTER TABLE ip_bans DROP INDEX uk_cidr_active, ADD UNIQUE KEY uk_cidr (cidr)");
        }
    } catch (Throwable $e) {
        // Never break the request over a missing table — the login flow
        // reports the failure cleanly below.
    }
}

function isIpWhitelisted(string $ip): bool {
    global $pdo;
    if (!$pdo) {
        return false;
    }
    ensureBanTable();
    $version = ipVersion($ip);
    try {
        $stmt = $pdo->prepare(
            "SELECT * FROM ip_bans
             WHERE active = 1 AND whitelisted = 1
             AND ip_version = ?
             ORDER BY created_at DESC"
        );
        $stmt->execute([$version]);
        while ($ban = $stmt->fetch()) {
            if (isIpInRange($ip, (string)($ban['ban_start'] ?? ''), (string)($ban['ban_end'] ?? ''))) {
                return true;
            }
        }
    } catch (Throwable $e) {
        return false;
    }
    return false;
}

function getBanForIp(string $ip): ?array {
    global $pdo;
    if (!$pdo) {
        return null;
    }
    ensureBanTable();
    $version = ipVersion($ip);
    $stmt = $pdo->prepare(
        "SELECT * FROM ip_bans
         WHERE active = 1
         AND whitelisted = 0
         AND ip_version = ?
         ORDER BY created_at DESC"
    );
    $stmt->execute([$version]);
    // Numeric range comparison in PHP (see isIpInRange) — SQL string
    // comparison on ban_start/ban_end is unreliable for IPs.
    while ($ban = $stmt->fetch()) {
        if (isIpInRange($ip, (string)($ban['ban_start'] ?? ''), (string)($ban['ban_end'] ?? ''))) {
            return $ban;
        }
    }
    return null;
}

function queueMail(string $to, string $subject, string $body): void {
    queueMailHtml($to, $subject, $body, '');
}

// ─── Transactional Email Engine (branded HTML templates + queue) ────────────
// Emails are queued to mail_queue (plain-text body + optional branded HTML),
// sent by the cron worker (send-mail.php) using the PRIMARY transport with the
// secondary as automatic fallback. Templates are overridable from the admin
// dashboard (email_template_<key>_subject / _body settings) and every email is
// wrapped in a branded, responsive HTML shell (logo header + social footer).

/** Idempotently add the html column to mail_queue (fresh + existing installs). */
function ensureMailQueueHtmlColumn(): void {
    global $pdo;
    if (!$pdo instanceof PDO) {
        return;
    }
    static $checked = false;
    if ($checked) {
        return;
    }
    $checked = true;
    try {
        $cols = $pdo->query("SHOW COLUMNS FROM mail_queue")->fetchAll(PDO::FETCH_COLUMN);
        if (!in_array('html', $cols, true)) {
            $pdo->exec("ALTER TABLE mail_queue ADD COLUMN html MEDIUMTEXT NULL AFTER body");
        }
        if (!in_array('from_email', $cols, true)) {
            $pdo->exec("ALTER TABLE mail_queue ADD COLUMN from_email VARCHAR(255) DEFAULT NULL AFTER html");
        }
        if (!in_array('from_name', $cols, true)) {
            $pdo->exec("ALTER TABLE mail_queue ADD COLUMN from_name VARCHAR(120) DEFAULT NULL AFTER from_email");
        }
    } catch (Throwable $e) {
        // Table may not exist yet on a fresh install — install.php creates it.
    }
}

/**
 * Queue a transactional email — plain-text body plus an optional branded HTML
 * body. Per-row From identity is supported (used by donation receipts) and
 * falls back to the global identity when omitted.
 */
function queueMailHtml(string $to, string $subject, string $body, string $html = '', ?string $fromName = null, ?string $fromEmail = null): void {
    global $pdo;
    if (!$pdo || empty($to)) {
        return;
    }
    ensureMailQueueHtmlColumn();
    try {
        $stmt = $pdo->prepare(
            "INSERT INTO mail_queue (id, to_email, subject, body, html, from_email, from_name, sent) VALUES (?, ?, ?, ?, ?, ?, ?, 0)"
        );
        $stmt->execute([generateId(), $to, $subject, $body, $html, $fromEmail, $fromName]);
    } catch (Throwable $e) {
        // Never break the caller over a best-effort email queue.
    }
}

/** Build an absolute URL from the current request host (emails need absolute links). */
function siteAbsoluteUrl(string $path = ''): string {
    $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
    return $scheme . '://' . $host . '/' . ltrim($path, '/');
}

/** Resolve the site logo URL used in the branded email header (setting overrides packaged logo). */
function siteLogoUrl(): string {
    $logo = trim((string)getSetting('site_logo_url', ''));
    if ($logo !== '') {
        return str_starts_with($logo, 'http') || str_starts_with($logo, 'data:') ? $logo : siteAbsoluteUrl($logo);
    }
    return siteAbsoluteUrl('assets/images/dailyimpact.png');
}

/** Social profile URLs used in the branded email footer (settings overridable). */
function emailSocialLinks(): array {
    return [
        'facebook'  => (string)getSetting('social_facebook', 'https://facebook.com/andrewosakwe'),
        'twitter'   => (string)getSetting('social_twitter', 'https://twitter.com/andrewosakwe'),
        'instagram' => (string)getSetting('social_instagram', 'https://instagram.com/andrewosakwe'),
        'youtube'   => (string)getSetting('social_youtube', 'https://youtube.com/andrewosakwe'),
    ];
}

/**
 * The From identity ({name} <{email}>). Donation-specific override applies when
 * $scope === 'donation' and the admin configured one; otherwise the general
 * identity (resend_from_name / resend_from_email) is used everywhere.
 */
function emailFromIdentity(string $scope = 'general'): array {
    $name  = (string)getSetting('resend_from_name', 'Daily Impact Devotional');
    $email = (string)getSetting('resend_from_email', '');
    if ($scope === 'donation') {
        $dName  = (string)getSetting('donation_from_name', '');
        $dEmail = (string)getSetting('donation_from_email', '');
        if ($dEmail !== '') {
            $name  = $dName !== '' ? $dName : $name;
            $email = $dEmail;
        }
    }
    return ['name' => $name, 'email' => $email];
}

/**
 * Idempotently create the login_logs table if it is missing, and add the
 * columns the login/audit flow depends on. Older deployments (pre-login-audit
 * database.sql) have no table at all, which made admin.php's INSERT and
 * login-log.php's SELECT throw on every request — the Admin Login Audit Log
 * silently stayed empty. Self-healing here means a stale database starts
 * recording logins immediately, no re-install.
 */
function ensureLoginLogTable(): void {
    global $pdo;
    if (!$pdo instanceof PDO) {
        return;
    }
    static $checked = false;
    if ($checked) {
        return;
    }
    $checked = true;
    try {
        $pdo->exec(
            "CREATE TABLE IF NOT EXISTS login_logs (
                id VARCHAR(36) PRIMARY KEY,
                email VARCHAR(255) NOT NULL,
                ip_address VARCHAR(45),
                user_agent TEXT,
                location VARCHAR(255),
                success TINYINT(1) DEFAULT 0,
                logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                INDEX idx_email (email),
                INDEX idx_logged_at (logged_at)
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
        );
        $cols = $pdo->query("SHOW COLUMNS FROM login_logs")->fetchAll(PDO::FETCH_COLUMN);
        if (!in_array('ip_address', $cols, true)) {
            $pdo->exec("ALTER TABLE login_logs ADD COLUMN ip_address VARCHAR(45) DEFAULT NULL AFTER email");
        }
        if (!in_array('location', $cols, true)) {
            $pdo->exec("ALTER TABLE login_logs ADD COLUMN location VARCHAR(255) DEFAULT NULL AFTER user_agent");
        }
        if (!in_array('logged_at', $cols, true)) {
            $pdo->exec("ALTER TABLE login_logs ADD COLUMN logged_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP AFTER success");
        }
    } catch (Throwable $e) {
        // Table may not exist yet on a brand-new install — install.php creates it.
    }
}

function recordIpBan(string $ip, string $reason, string $email = '', int $failedAttempts = 0, string $source = 'admin-login'): ?array {
    global $pdo;
    if (!$pdo) {
        return null;
    }
    // Whitelisted IPs are never banned — an admin explicitly allowed them.
    if (isIpWhitelisted($ip)) {
        return null;
    }
    $cidr = normalizeSubnet($ip);
    [$banStart, $banEnd] = ipRangeForSubnet($cidr);
    $version = ipVersion($ip);
    ensureBanTable();
    $stmt = $pdo->prepare(
        "INSERT INTO ip_bans
            (id, ip_address, ip_version, cidr, ban_start, ban_end, reason, source, email, failed_attempts, active)
         VALUES
            (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
         ON DUPLICATE KEY UPDATE
            reason = VALUES(reason),
            source = VALUES(source),
            email = VALUES(email),
            failed_attempts = GREATEST(failed_attempts, VALUES(failed_attempts)),
            active = 1,
            unbanned_at = NULL,
            unbanned_by = NULL"
    );
    $stmt->execute([
        generateId(),
        $ip,
        $version,
        $cidr,
        $banStart,
        $banEnd,
        $reason,
        $source,
        $email,
        $failedAttempts,
    ]);

    $lookup = $pdo->prepare("SELECT * FROM ip_bans WHERE cidr = ? AND active = 1 ORDER BY created_at DESC LIMIT 1");
    $lookup->execute([$cidr]);
    return $lookup->fetch() ?: null;
}

function unbanIpBan(string $id, ?string $adminEmail = null): bool {
    global $pdo;
    if (!$pdo) {
        return false;
    }
    try {
        ensureBanTable();
        $stmt = $pdo->prepare(
            "UPDATE ip_bans SET active = 0, unbanned_at = NOW(), unbanned_by = ? WHERE id = ?"
        );
        $stmt->execute([$adminEmail, $id]);
        return true;
    } catch (Throwable $e) {
        return false;
    }
}

// ─── Real MIME detection ────────────────────────────────────────────────────
function detectRealMime(string $filePath, string $fallbackMime = 'application/octet-stream'): string {
    if (function_exists('finfo_open')) {
        $finfo = finfo_open(FILEINFO_MIME_TYPE);
        if ($finfo) {
            $mime = finfo_file($finfo, $filePath);
            finfo_close($finfo);
            return $mime ?: $fallbackMime;
        }
    }
    // finfo not available — fall back to client-supplied MIME or octet-stream
    return $fallbackMime;
}

// ─── Session Security ─────────────────────────────────────────────────────

/**
 * Configure secure session settings.
 * Call BEFORE session_start().
 */
function configureSession(): void {
    // Detect HTTPS robustly: direct TLS, reverse proxies (X-Forwarded-Proto)
    // and Cloudflare (CF-Visitor). Marking the cookie Secure when the browser
    // is actually on HTTP silently drops it and kills the session — the exact
    // "login first" loop admins hit behind Cloudflare Flexible SSL on cPanel.
    $secure = false;
    $https = (string)($_SERVER['HTTPS'] ?? '');
    if ($https !== '' && $https !== 'off') $secure = true;
    if ((string)($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? '') === 'https') $secure = true;
    if (str_contains((string)($_SERVER['HTTP_CF_VISITOR'] ?? ''), '"https"')) $secure = true;

    $cookieParams = session_get_cookie_params();
    session_set_cookie_params([
        'lifetime' => 0, // until browser closes
        'path'     => $cookieParams['path'] ?? '/',
        'domain'   => $cookieParams['domain'] ?? '',
        'secure'   => $secure,
        'httponly' => true,
        'samesite' => 'Lax', // Strict can break the cookie when a page opens via a redirect chain
    ]);

    // Use a project-relative session save path so sessions persist on cPanel
    // (default /tmp may not be writable or may be cleared between requests)
    $sessionDir = __DIR__ . '/../../tmp/sessions';
    if (!is_dir($sessionDir)) {
        @mkdir($sessionDir, 0777, true);
    }
    if (is_dir($sessionDir) && is_writable($sessionDir)) {
        session_save_path($sessionDir);
    }
}

/**
 * Check session idle timeout.
 * Destroys session if more than SESSION_LIFETIME seconds idle.
 * Updates last_activity timestamp on success.
 */
function checkSessionTimeout(int $maxIdleSeconds = 3600): void {
    if (session_status() !== PHP_SESSION_ACTIVE) {
        return;
    }
    $lastActivity = $_SESSION['last_activity'] ?? 0;
    if ($lastActivity > 0 && (time() - $lastActivity) > $maxIdleSeconds) {
        // Session expired — destroy
        $_SESSION = [];
        session_destroy();
        return;
    }
    // Update last activity
    $_SESSION['last_activity'] = time();
}

/**
 * Regenerate session ID to prevent session fixation.
 * Preserves all session data.
 */
function regenerateSession(): void {
    if (session_status() === PHP_SESSION_ACTIVE) {
        session_regenerate_id(true);
    }
}

/**
 * Bind session to client identity (User-Agent + IP subnet) and return true
 * if the session fingerprint matches.
 *
 * Subnet-level (instead of exact-IP) binding keeps sessions alive behind
 * Cloudflare / rotating proxy edges and IPv6 privacy extensions, where the
 * exact remote address can legitimately change between requests — previously
 * that destroyed sessions and made admin-only data (like decrypted Telegram
 * credentials in settings.php) "disappear" after reload/logout.
 */
function sessionFingerprint(): string {
    $ip = getClientIp();
    $ua = $_SERVER['HTTP_USER_AGENT'] ?? '';
    return hash('sha256', normalizeSubnet($ip) . '|' . $ua);
}

function validateSessionBinding(): bool {
    if (session_status() !== PHP_SESSION_ACTIVE) {
        return false;
    }
    $fingerprint = sessionFingerprint();

    if (!isset($_SESSION['session_fingerprint'])) {
        // First check — set fingerprint
        $_SESSION['session_fingerprint'] = $fingerprint;
        return true;
    }

    return hash_equals($_SESSION['session_fingerprint'], $fingerprint);
}

/**
 * Full session hardening: configure, start, validate.
 * Call at the start of every admin-protected page.
 * 
 * @param int $maxIdleSeconds Session idle timeout (default 60 min)
 * @return bool True if session is valid
 */
function secureSession(int $maxIdleSeconds = 3600): bool {
    if (session_status() === PHP_SESSION_NONE) {
        configureSession();
        session_start();
    }

    // Check idle timeout
    checkSessionTimeout($maxIdleSeconds);

    // If no admin session, nothing to validate
    if (!isset($_SESSION['admin_id'])) {
        return false;
    }

    // Absolute lifetime cap: even with constant activity, a session dies after
    // 24 hours. A stolen session cookie can never stay valid indefinitely.
    $sessionCreated = (int)($_SESSION['created_at'] ?? 0);
    if ($sessionCreated > 0 && (time() - $sessionCreated) > 86400) {
        $_SESSION = [];
        session_destroy();
        return false;
    }

    // Validate fingerprint binding
    if (!validateSessionBinding()) {
        // Possible hijack — destroy session
        $_SESSION = [];
        session_destroy();
        return false;
    }

    // Hard ban guard: a banned IP loses admin access EVEN with a live session.
    // This backs up the login-gate check so a ban takes effect instantly on
    // every admin API call (dashboard, settings, telegram, payments, ...),
    // while the public website stays fully browsable for that IP.
    $ban = getBanForIp(getClientIp());
    if ($ban !== null) {
        $_SESSION = [];
        session_destroy();
        return false;
    }

    // Session-version guard: when an admin bumps session_version ("log out all
    // sessions" from the login-notification email), every pre-existing session
    // for that user becomes invalid and is destroyed on its next API call.
    if (!empty($_SESSION['admin_id'])) {
        try {
            ensureSessionVersionColumn();
            $stmt = $pdo->prepare("SELECT session_version FROM admin_users WHERE id = ?");
            $stmt->execute([$_SESSION['admin_id']]);
            $current = $stmt->fetchColumn();
            if ($current !== false && (int)$current !== (int)($_SESSION['admin_session_version'] ?? 0)) {
                $_SESSION = [];
                session_destroy();
                return false;
            }
        } catch (Throwable $e) {
            // Version column may not exist yet on a partially-migrated DB —
            // never lock admins out over the version check.
        }
    }

    return true;
}

// ─── Two-Factor Authentication (2FA) ────────────────────────────────────────
// Real, server-verified 2FA: TOTP (authenticator app, RFC 6238) and Email OTP.
// Secrets/backup codes live on the admin_users row; OTPs are verified server-
// side so a client can never self-activate or bypass verification. Backup codes
// are stored as SHA-256 hashes and consumed on use.

/**
 * Idempotently add the 2FA columns to admin_users (fresh + existing installs).
 */
function ensureTwoFaColumns(): void {
    global $pdo;
    if (!$pdo instanceof PDO) {
        return;
    }
    static $checked = false;
    if ($checked) {
        return;
    }
    $checked = true;
    try {
        $cols = $pdo->query("SHOW COLUMNS FROM admin_users")->fetchAll(PDO::FETCH_COLUMN);
        if (!in_array('totp_secret', $cols, true)) {
            $pdo->exec("ALTER TABLE admin_users ADD COLUMN totp_secret VARCHAR(255) NOT NULL DEFAULT '' AFTER status");
        }
        if (!in_array('totp_enabled', $cols, true)) {
            $pdo->exec("ALTER TABLE admin_users ADD COLUMN totp_enabled TINYINT(1) NOT NULL DEFAULT 0 AFTER totp_secret");
        }
        if (!in_array('email_otp_enabled', $cols, true)) {
            $pdo->exec("ALTER TABLE admin_users ADD COLUMN email_otp_enabled TINYINT(1) NOT NULL DEFAULT 0 AFTER totp_enabled");
        }
        if (!in_array('backup_codes', $cols, true)) {
            $pdo->exec("ALTER TABLE admin_users ADD COLUMN backup_codes TEXT NULL AFTER email_otp_enabled");
        }
    } catch (Throwable $e) {
        // Table may not exist yet on a fresh install — install.php creates it.
    }
}

// ── TOTP (RFC 6238) — pure PHP, no extensions beyond hash_hmac ───────────────

function base32Decode(string $b32): string {
    $alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
    $b32 = strtoupper((string)preg_replace('/[^A-Z2-7]/', '', $b32));
    if ($b32 === '') {
        return '';
    }
    $buffer = 0;
    $bitsLeft = 0;
    $out = '';
    $len = strlen($b32);
    for ($i = 0; $i < $len; $i++) {
        $val = strpos($alphabet, $b32[$i]);
        if ($val === false) {
            continue;
        }
        $buffer = ($buffer << 5) | $val;
        $bitsLeft += 5;
        if ($bitsLeft >= 8) {
            $out .= chr(($buffer >> ($bitsLeft - 8)) & 0xFF);
            $bitsLeft -= 8;
        }
    }
    return $out;
}

/** Generate a 160-bit base32 TOTP secret (32 chars — standard for 2FA apps). */
function generateTotpSecret(): string {
    $alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
    $secret = '';
    $random = random_bytes(20);
    for ($i = 0; $i < 20; $i++) {
        $secret .= $alphabet[ord($random[$i]) % 32];
    }
    return $secret;
}

/** RFC 6238 code for a given timestamp (default: 6 digits, 30s period). */
function totpCode(string $secret, int $timestamp, int $period = 30, int $digits = 6): string {
    $counter = intdiv($timestamp, $period);
    // 8-byte big-endian counter (two 32-bit words — fine until year ~2042).
    $bin = pack('N2', 0, $counter);
    $key = base32Decode($secret);
    $hash = hash_hmac('sha1', $bin, $key, true);
    $offset = ord($hash[strlen($hash) - 1]) & 0x0F;
    $value = ((ord($hash[$offset]) & 0x7F) << 24)
           | ((ord($hash[$offset + 1]) & 0xFF) << 16)
           | ((ord($hash[$offset + 2]) & 0xFF) << 8)
           | (ord($hash[$offset + 3]) & 0xFF);
    return str_pad((string)($value % (10 ** $digits)), $digits, '0', STR_PAD_LEFT);
}

/** Verify a TOTP code allowing +/- $window time-steps of clock drift. */
function verifyTotp(string $secret, string $code, int $window = 1): bool {
    $code = preg_replace('/\D/', '', (string)$code);
    if ($secret === '' || strlen($code) !== 6) {
        return false;
    }
    $t = time();
    for ($w = -$window; $w <= $window; $w++) {
        if (hash_equals(totpCode($secret, $t + ($w * 30)), $code)) {
            return true;
        }
    }
    return false;
}

// ── Backup / recovery codes ───────────────────────────────────────────────────

/** Generate N one-time recovery codes (8 uppercase hex chars each). */
function generateBackupCodes(int $count = 5): array {
    $codes = [];
    for ($i = 0; $i < $count; $i++) {
        $codes[] = strtoupper(bin2hex(random_bytes(4)));
    }
    return $codes;
}

function hashBackupCode(string $code): string {
    return hash('sha256', strtoupper(trim($code)));
}

/**
 * Consume a recovery code for the given admin row. Returns the number of codes
 * REMAINING after consumption, or null when the code is invalid/absent.
 * Persists the updated list to the DB.
 */
function consumeBackupCode(array $admin, string $code): ?int {
    global $pdo;
    if (!$pdo instanceof PDO) {
        return null;
    }
    $hashes = json_decode((string)($admin['backup_codes'] ?? '[]'), true);
    if (!is_array($hashes) || count($hashes) === 0) {
        return null;
    }
    $target = hashBackupCode($code);
    $idx = null;
    foreach ($hashes as $i => $h) {
        if (is_string($h) && hash_equals($h, $target)) {
            $idx = $i;
            break;
        }
    }
    if ($idx === null) {
        return null;
    }
    array_splice($hashes, $idx, 1);
    try {
        $stmt = $pdo->prepare("UPDATE admin_users SET backup_codes = ? WHERE id = ?");
        $stmt->execute([json_encode(array_values($hashes)), (int)$admin['id']]);
    } catch (Throwable $e) {
        return null;
    }
    return count($hashes);
}

/**
 * Shared alert throttle: returns TRUE when an alert may be sent now (not
 * throttled) and records the send. The map lives in one settings key and is
 * pruned to 7 days so the settings table never grows unbounded. Used by the
 * failed-login email alerts (admin.php + login-log.php) to stop an attacker
 * flooding admin inboxes.
 */
function alertNotThrottled(string $mapKey, string $subjectHash, int $windowSec = 1800): bool
{
    try {
        $saved = getSetting($mapKey, '{}');
        $map = json_decode((string)$saved, true);
        if (!is_array($map)) {
            $map = [];
        }
        $now = time();
        foreach ($map as $k => $ts) {
            if ($now - (int)$ts > 604800) unset($map[$k]);
        }
        if (isset($map[$subjectHash]) && ($now - (int)$map[$subjectHash]) < $windowSec) {
            return false;
        }
        $map[$subjectHash] = $now;
        setSetting($mapKey, json_encode($map));
        return true;
    } catch (Throwable $e) {
        return true; // never block an alert because of storage problems
    }
}

/**
 * Idempotently add the session_version column to admin_users.
 *
 * session_version powers "log out all sessions": bumping it invalidates every
 * existing PHP session for that user, because secureSession() compares the
 * version stored in the session against the user's row and destroys the
 * session on mismatch. Sessions themselves are file-based on cPanel, so they
 * can't be enumerated — the version stamp is the reliable way to revoke them.
 */
function ensureSessionVersionColumn(): void {
    global $pdo;
    if (!$pdo instanceof PDO) {
        return;
    }
    static $checked = false;
    if ($checked) {
        return;
    }
    $checked = true;
    try {
        $cols = $pdo->query("SHOW COLUMNS FROM admin_users")->fetchAll(PDO::FETCH_COLUMN);
        if (!in_array('session_version', $cols, true)) {
            $pdo->exec("ALTER TABLE admin_users ADD COLUMN session_version INT NOT NULL DEFAULT 0 AFTER backup_codes");
        }
    } catch (Throwable $e) {
        // Table may not exist yet on a fresh install — install.php creates it.
    }
}

/** Current 2FA status for an admin_users row. */
function twofaStatusForUser(array $admin): array {
    $methods = [];
    if ((int)($admin['totp_enabled'] ?? 0) === 1) {
        $methods[] = 'app';
    }
    if ((int)($admin['email_otp_enabled'] ?? 0) === 1) {
        $methods[] = 'email';
    }
    $codes = json_decode((string)($admin['backup_codes'] ?? '[]'), true);
    $remaining = is_array($codes) ? count($codes) : 0;
    return [
        'enabled'         => count($methods) > 0,
        'methods'         => $methods,
        'backupRemaining' => $remaining,
    ];
}

/**
 * Complete an admin login: regenerate the session id, bind the fingerprint,
 * populate session vars and clear any pending-2FA / lockout state. Shared by
 * the plain login path and the post-2FA-verification path so both behave
 * identically.
 */
function establishAdminSession(array $admin): void {
    regenerateSession();
    $fingerprint = sessionFingerprint();
    $_SESSION['admin_id']            = $admin['id'];
    $_SESSION['admin_email']         = $admin['email'];
    $_SESSION['admin_name']          = $admin['name'];
    $_SESSION['admin_bio']           = (string)($admin['bio'] ?? '');
    $_SESSION['admin_role']          = $admin['role'];
    $_SESSION['session_fingerprint'] = $fingerprint;
    $_SESSION['last_activity']       = time();
    $_SESSION['created_at']          = time();
    $_SESSION['admin_session_version'] = (int)($admin['session_version'] ?? 0);
    unset(
        $_SESSION['pending_2fa'],
        $_SESSION['2fa_attempts'],
        $_SESSION['2fa_email_code_hash'],
        $_SESSION['2fa_email_expires'],
        $_SESSION['2fa_email_attempts']
    );

    // Clear any lockout for this IP (mirrors the old inline login code).
    $ip = getClientIp();
    $lockKey = 'login_lock_' . preg_replace('/[^a-f0-9]/', '', hash('sha256', $ip));
    try {
        setSetting($lockKey, '0');
    } catch (Throwable $e) {
        // best-effort
    }
}

// ─── Donation columns (idempotent migration) ─────────────────────────────────
// Older databases predate the donor phone number and anonymous-flag columns.
// Instead of forcing a re-install, add them on demand — donations.php calls
// this on every request so stale DBs self-heal on the first donation.
function ensureDonationColumns(): void {
    global $pdo;
    if (!$pdo instanceof PDO) {
        return;
    }
    static $checked = false;
    if ($checked) {
        return;
    }
    $checked = true;
    try {
        $cols = $pdo->query("SHOW COLUMNS FROM donations")->fetchAll(PDO::FETCH_COLUMN);
        if (!in_array('phone', $cols, true)) {
            $pdo->exec("ALTER TABLE donations ADD COLUMN phone VARCHAR(40) DEFAULT '' AFTER name");
        }
        if (!in_array('is_anonymous', $cols, true)) {
            $pdo->exec("ALTER TABLE donations ADD COLUMN is_anonymous TINYINT(1) NOT NULL DEFAULT 0 AFTER phone");
        }
    } catch (Throwable $e) {
        // Table may not exist yet on a fresh install — install.php creates it.
    }
}

// ─── Real-Time Activity Log & Reactions (idempotent table creation) ─────────
function ensureActivityTables(): void {
    global $pdo;
    if (!$pdo instanceof PDO) return;
    // Run the DDL only once per PHP process. reactions.php is a hot, public
    // endpoint (every visitor click), so we must not fire CREATE TABLE on
    // each request — a static flag keeps it a one-time setup.
    static $checked = false;
    if ($checked) return;
    try {
        $pdo->exec("CREATE TABLE IF NOT EXISTS activity_log (
            id VARCHAR(36) PRIMARY KEY,
            action VARCHAR(50) NOT NULL,
            message TEXT NOT NULL,
            entity_type VARCHAR(50) DEFAULT '',
            entity_id VARCHAR(255) DEFAULT '',
            actor VARCHAR(255) DEFAULT '',
            ip_address VARCHAR(45) DEFAULT '',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_created (created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
        $pdo->exec("CREATE TABLE IF NOT EXISTS devotional_reaction_votes (
            id INT AUTO_INCREMENT PRIMARY KEY,
            devotional_id VARCHAR(36) NOT NULL,
            emoji VARCHAR(32) NOT NULL,
            ip_hash CHAR(64) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uk_vote (devotional_id, ip_hash),
            INDEX idx_devotional (devotional_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");

        // Single-selection migration: older installs had ONE vote per
        // (devotional, emoji, IP) — a visitor could hold several reactions on
        // the same devotional at once. New behavior allows only ONE reaction
        // per (devotional, IP); clicking a new emoji replaces the old one.
        // Detect the legacy 3-column key (or a missing key left by a partial
        // earlier run) and rebuild it idempotently, keeping the visitor's
        // most recent vote if duplicates exist.
        $idx = $pdo->query("SHOW INDEX FROM devotional_reaction_votes WHERE Key_name = 'uk_vote'");
        $keyCols = $idx ? $idx->fetchAll(PDO::FETCH_ASSOC) : [];
        $hasEmojiInKey = false;
        foreach ($keyCols as $col) {
            // Column_name casing differs between MySQL/MariaDB and PDO modes.
            $colName = strtolower((string)($col['Column_name'] ?? $col['column_name'] ?? ''));
            if ($colName === 'emoji') {
                $hasEmojiInKey = true;
                break;
            }
        }
        // Rebuild if the key still contains emoji (legacy) OR is missing
        // entirely (a prior DROP succeeded but ADD failed). A correct 2-column
        // key has exactly devotional_id + ip_hash and no emoji.
        if ($hasEmojiInKey || count($keyCols) === 0) {
            // Keep only the newest vote per (devotional, IP) before enforcing
            // the new unique constraint (dedupe any legacy multi-reactions).
            $pdo->exec(
                "DELETE v1 FROM devotional_reaction_votes v1
                 INNER JOIN devotional_reaction_votes v2
                    ON v1.devotional_id = v2.devotional_id
                   AND v1.ip_hash = v2.ip_hash
                   AND v1.id < v2.id"
            );
            // DROP is best-effort: the key may already be gone from a partial
            // earlier run. If it still exists, remove it; if not, ignore.
            try {
                $pdo->exec("ALTER TABLE devotional_reaction_votes DROP INDEX uk_vote");
            } catch (Throwable $e) {
                // index may not exist — that's fine, we're about to add it
            }
            $pdo->exec("ALTER TABLE devotional_reaction_votes ADD UNIQUE KEY uk_vote (devotional_id, ip_hash)");
        }
    } catch (Throwable $e) {
        // Tables may not exist yet on brand-new installs — install.php creates them.
        return;
    }
    $checked = true;
}

/**
 * Append a real activity entry. Called from admin/devotionals/headers/telegram
 * endpoints so the dashboard's log feed shows genuine, real-time events.
 * Never throws — logging must never break the request that triggered it.
 */
function logActivity(string $action, string $message, string $entityType = '', string $entityId = '', string $actor = ''): void {
    global $pdo;
    if (!$pdo instanceof PDO) return;
    ensureActivityTables();
    if ($actor === '') {
        $actor = trim((string)($_SESSION['admin_name'] ?? '')) !== ''
            ? (string)$_SESSION['admin_name']
            : (string)($_SESSION['admin_email'] ?? '');
    }
    try {
        $stmt = $pdo->prepare(
            "INSERT INTO activity_log (id, action, message, entity_type, entity_id, actor, ip_address)
             VALUES (?, ?, ?, ?, ?, ?, ?)"
        );
        $stmt->execute([
            generateId(),
            substr($action, 0, 50),
            substr($message, 0, 1000),
            substr($entityType, 0, 50),
            substr($entityId, 0, 255),
            $actor,
            getClientIp(),
        ]);
    } catch (Throwable $e) {
        // ignore — logging is best-effort
    }
}

// ─── Parse date parts from "July 20" format ─────────────────────────────────
function parseDateParts(string $dateStr): array {
    $months = [
        'january', 'february', 'march', 'april', 'may', 'june',
        'july', 'august', 'september', 'october', 'november', 'december'
    ];
    $dateStr = trim($dateStr);
    
    // Match "Month Day" pattern
    if (preg_match('/^([A-Za-z]+)\s+(\d+)/i', $dateStr, $m)) {
        return [
            'month' => ucfirst(strtolower($m[1])),
            'day'   => (int)$m[2],
        ];
    }
    
    // Match "Day Month" pattern
    if (preg_match('/^(\d+)\s+([A-Za-z]+)/i', $dateStr, $m)) {
        return [
            'month' => ucfirst(strtolower($m[2])),
            'day'   => (int)$m[1],
        ];
    }
    
    // Fallback: try to find month name
    $lower = strtolower($dateStr);
    foreach ($months as $month) {
        if (strpos($lower, $month) !== false) {
            preg_match('/\d+/', $dateStr, $dm);
            return [
                'month' => ucfirst($month),
                'day'   => isset($dm[0]) ? (int)$dm[0] : 1,
            ];
        }
    }
    
    return ['month' => 'January', 'day' => 1];
}

// ─── Email Template Engine (branded HTML emails + CSV export helper) ────────
// All functions are defined in this include so db.php stays small and the
// large HTML templates live in one place. It only defines functions — nothing
// executes — so including it here is safe for every consumer of db.php.
require_once __DIR__ . '/email-templates.php';
