<?php
/**
 * Daily Impact Devotional - Database Configuration
 * 
 * This file is auto-generated by install.php.
 * Edit it manually only if you know what you're doing.
 */

// ─── Database Credentials (edit these or use install.php) ───────────────────
$db_host = 'localhost';
$db_name = 'dailyimpact_devotional';
$db_user = 'root';
$db_pass = '';

// ─── File Upload Directory (relative to project root) ───────────────────────
// cPanel deployment uses /upload with dedicated subfolders.
define('UPLOADS_DIR', __DIR__ . '/../../upload');
define('HEADERS_DIR', UPLOADS_DIR . '/headers');
// NOTE: the actual folder created & used for devotional DOCX files is
// 'upload/devotionals' (plural) — kept consistent everywhere (upload.php,
// health.php, install.php). The old 'devotional' (singular) folder is unused.
define('DEVOTIONALS_DIR', UPLOADS_DIR . '/devotionals');

// ─── JSON-only error handling ───────────────────────────────────────────────
// The API must never leak PHP warnings or fatal HTML error pages. Suppress
// inline output, then convert uncaught exceptions and fatal errors into JSON.
ini_set('display_errors', '0');
error_reporting(E_ALL);

set_exception_handler(function (Throwable $e): void {
    http_response_code(500);
    if (!headers_sent()) {
        header('Content-Type: application/json; charset=utf-8');
    }
    $msg = $e->getMessage();
    // Same contract as jsonError(): {success:false, message, error}
    echo json_encode(['success' => false, 'message' => $msg, 'error' => $msg]);
    exit;
});

register_shutdown_function(function (): void {
    $err = error_get_last();
    if ($err && in_array($err['type'], [E_ERROR, E_PARSE, E_CORE_ERROR, E_COMPILE_ERROR], true)) {
        http_response_code(500);
        if (!headers_sent()) {
            header('Content-Type: application/json; charset=utf-8');
        }
        $msg = 'Server error: ' . $err['message'];
        // Same contract as jsonError(): {success:false, message, error}
        echo json_encode(['success' => false, 'message' => $msg, 'error' => $msg]);
    }
});

// ─── PDO Connection ─────────────────────────────────────────────────────────
try {
    $pdo = new PDO(
        "mysql:host=$db_host;dbname=$db_name;charset=utf8mb4",
        $db_user,
        $db_pass,
        [
            PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            PDO::ATTR_EMULATE_PREPARES   => false,
        ]
    );
} catch (PDOException $e) {
    // Don't exit here — let the calling endpoint decide how to respond.
    // If config is loaded before DB is ready, all functions below still need to exist.
    $pdo = null;
    $GLOBALS['db_error'] = $e->getMessage();
}

// ─── CORS Headers ───────────────────────────────────────────────────────────
function sendCorsHeaders(): void {
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS');
    header('Access-Control-Allow-Headers: Content-Type, Authorization');
    header('Content-Type: application/json; charset=utf-8');

    // API responses must never be cached by the browser/proxy — otherwise a
    // stale GET /devotionals.php response can resurrect a row the admin just
    // deleted ("deleted it, then it came back").
    header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
    header('Pragma: no-cache');

    if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
        http_response_code(200);
        exit;
    }
}

// Resolve the effective HTTP method. Some shared hosts (cPanel/ModSecurity)
// block the DELETE/PUT verbs outright, so the frontend falls back to sending
// POST with ?_method=DELETE (or ?_method=PUT). All DELETE/PUT handlers require
// an admin session, so honoring this override is safe.
function httpMethod(): string {
    $m = strtoupper($_SERVER['REQUEST_METHOD'] ?? 'GET');
    if ($m === 'POST') {
        $override = $_GET['_method'] ?? '';
        if (is_string($override) && in_array(strtoupper($override), ['PUT', 'DELETE'], true)) {
            return strtoupper($override);
        }
    }
    return $m;
}

// ─── JSON Helpers ───────────────────────────────────────────────────────────
function jsonInput(): array {
    $raw = file_get_contents('php://input');
    if (empty($raw)) {
        return [];
    }
    $data = json_decode($raw, true);
    if (!is_array($data)) {
        jsonError('Invalid JSON body', 400);
    }
    return $data;
}

function jsonResponse(mixed $data, int $code = 200): void {
    http_response_code($code);
    // JSON_INVALID_UTF8_SUBSTITUTE: imported DOCX content can contain invalid
    // UTF-8 bytes; without this flag json_encode() returns false and the whole
    // response goes blank — which previously made devotionals "disappear" from
    // the admin dashboard (and homepage) after reload while DB rows remained.
    echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_INVALID_UTF8_SUBSTITUTE);
    exit;
}

// ─── UTF-8 Sanitizer ─────────────────────────────────────────────────────────
// Strips invalid UTF-8 byte sequences from imported text (DOCX parsing, manual
// pastes) so JSON responses and json_encode() never fail on bad bytes.
function utf8Safe(mixed $value): mixed {
    if (is_array($value)) {
        foreach ($value as $k => $v) {
            $value[$k] = utf8Safe($v);
        }
        return $value;
    }
    if (is_string($value)) {
        // Fast path: the overwhelming majority of content is already valid
        // UTF-8. A single /u regex check is far cheaper than iconv() per field,
        // so we only pay the iconv cost for genuinely broken strings (imported
        // DOCX content). This makes the GET /devotionals response dramatically
        // faster on shared hosting (hundreds of rows x many fields).
        if (preg_match('//u', $value)) {
            return $value;
        }
        // iconv //IGNORE drops invalid sequences; fall back to regex scrub.
        $clean = @iconv('UTF-8', 'UTF-8//IGNORE', $value);
        if ($clean !== false) {
            return $clean;
        }
        return preg_replace('/[\x00-\x08\x0B\x0C\x0E-\x1F]/u', '', $value) ?? $value;
    }
    return $value;
}

function jsonError(string $message, int $code = 400): void {
    // Documented contract: {success: false, message: ...}.
    // 'error' is kept for backward compatibility with older clients.
    jsonResponse([
        'success' => false,
        'message' => $message,
        'error'   => $message,
    ], $code);
}

// ─── Auth Helper ────────────────────────────────────────────────────────────
function requireAdmin(): void {
    // Use secureSession() for consistent session handling (configure, timeout check, IP binding)
    if (!secureSession()) {
        jsonError('Unauthorized. Please log in first.', 401);
    }
}

// ─── ID Generator ───────────────────────────────────────────────────────────
// Standard UUID v4 (36 chars) — fits the VARCHAR(36) id columns.
// (The old format produced 48 chars, which MySQL strict mode rejects.)
function generateId(): string {
    $data = random_bytes(16);
    $data[6] = chr((ord($data[6]) & 0x0f) | 0x40); // version 4
    $data[8] = chr((ord($data[8]) & 0x3f) | 0x80); // variant
    return vsprintf('%s%s-%s-%s-%s-%s%s%s', str_split(bin2hex($data), 4));
}

// ─── Settings Helper ────────────────────────────────────────────────────────
function requireDb(): void {
    global $pdo;
    if (!$pdo instanceof PDO) {
        throw new RuntimeException('Database connection failed. Check config/db.php credentials and database availability.');
    }
}

function getSettings(): array {
    requireDb();
    global $pdo;
    $stmt = $pdo->query("SELECT setting_key, setting_value FROM settings");
    $settings = [];
    while ($row = $stmt->fetch()) {
        $settings[$row['setting_key']] = $row['setting_value'];
    }
    // Secrets are stored encrypted — decrypt for all internal consumers.
    return decryptSettings($settings);
}

function getSetting(string $key, mixed $default = null): mixed {
    requireDb();
    global $pdo;
    $stmt = $pdo->prepare("SELECT setting_value FROM settings WHERE setting_key = ?");
    $stmt->execute([$key]);
    $val = $stmt->fetchColumn();
    if ($val === false) {
        return $default;
    }
    return isSecretSettingKey($key) ? decryptSecret($val) : $val;
}

function setSetting(string $key, string $value): void {
    requireDb();
    global $pdo;
    $stmt = $pdo->prepare(
        "INSERT INTO settings (setting_key, setting_value) VALUES (?, ?)
         ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value)"
    );
    $stmt->execute([$key, $value]);
}

// ─── Secret Encryption (AES-256-CBC) ───────────────────────────────────────
// Credentials (Telegram bot token, channel id, SMTP pass, payment secrets,
// webhook secret) are encrypted at rest so a DB dump alone can't leak them.
// The encryption key lives in a file OUTSIDE the web root (../secret.key,
// one level up from config/ — not web-accessible). getSettings()/getSetting()
// decrypt transparently, so all existing consumers keep working unchanged.

/** Setting keys whose values are stored encrypted. */
function secretSettingKeys(): array {
    return [
        'telegram_bot_token',
        'telegram_channel_id',
        'resend_api_key',
        'smtp_pass',
        'paystack_secret_key',
        'flutterwave_secret_key',
        'flutterwave_encryption_key',
        'webhook_secret',
    ];
}

function isSecretSettingKey(string $key): bool {
    return in_array($key, secretSettingKeys(), true);
}

/**
 * Load (or lazily create) the site's encryption key.
 *
 * The key is stored in config/secret.key.php — a PHP file that just returns
 * the key string. A direct web request to it executes PHP and outputs nothing
 * (the file is also denied by config/.htaccess), so the key can never be
 * downloaded as plain text even though config/ lives under public_html.
 *
 * If the file can't be written (e.g. first request on a locked-down host),
 * we fall back to a per-install derived key so nothing breaks — but we
 * always attempt to persist so subsequent requests use the stable file key.
 */
function encryptionKey(): string {
    static $key = null;
    if ($key !== null) {
        return $key;
    }

    $keyFile = __DIR__ . '/secret.key.php';
    if (is_file($keyFile)) {
        $stored = include $keyFile; // returns the key string
        if (is_string($stored) && strlen($stored) >= 32) {
            $key = $stored;
            return $key;
        }
    }

    // Generate a fresh 32-byte key (hex = 64 chars) and persist it as a PHP
    // file (executes to an empty page if ever hit directly via the web).
    // Exclusive-create ('x' mode): concurrent first requests can't each write
    // a different key — only ONE request wins the race; the losers re-read the
    // winner's file below. This keeps every request on the same persisted key.
    $generated = bin2hex(random_bytes(32));
    $phpContent = "<?php\n" .
        "// Auto-generated encryption key for Daily Impact Devotional.\n" .
        "// DO NOT EDIT OR DELETE — deleting it makes stored secrets undecryptable.\n" .
        "return '" . $generated . "';\n";
    $handle = @fopen($keyFile, 'x');
    if ($handle !== false) {
        fwrite($handle, $phpContent);
        fclose($handle);
        @chmod($keyFile, 0600);
        $key = $generated;
        return $key;
    }

    // Another request created the file first (fopen 'x' failed) — use it.
    if (is_file($keyFile)) {
        $stored = include $keyFile;
        if (is_string($stored) && strlen($stored) >= 32) {
            $key = $stored;
            return $key;
        }
    }

    // Fallback: derive a stable per-install key from the DB config. Only used
    // if the key file could not be created (should be rare on real hosts).
    global $db_host, $db_name, $db_user, $db_pass;
    $key = hash('sha256',
        ($db_host ?? 'localhost') . '|' . ($db_name ?? '') . '|' .
        ($db_user ?? '') . '|' . ($db_pass ?? '') . '|dailyimpact-secret'
    );
    return $key;
}

/** Encrypt a plaintext secret for storage. Empty stays empty. */
function encryptSecret(string $plain): string {
    if ($plain === '') {
        return '';
    }
    // Already encrypted (double-save safety) — return as-is.
    if (str_starts_with($plain, 'enc:v1:')) {
        return $plain;
    }
    $key = hash('sha256', encryptionKey(), true); // 32 raw bytes
    $iv  = random_bytes(16);
    $cipher = openssl_encrypt($plain, 'AES-256-CBC', $key, OPENSSL_RAW_DATA, $iv);
    if ($cipher === false) {
        // openssl missing — store plaintext rather than lose the value.
        return $plain;
    }
    return 'enc:v1:' . base64_encode($iv . $cipher);
}

/** Decrypt a stored secret. Handles plaintext (legacy) and empty values. */
function decryptSecret(string $stored): string {
    if ($stored === '' || !str_starts_with($stored, 'enc:v1:')) {
        return $stored; // empty or legacy plaintext
    }
    $raw = base64_decode(substr($stored, 7), true);
    if ($raw === false || strlen($raw) <= 16) {
        return '';
    }
    $iv     = substr($raw, 0, 16);
    $cipher = substr($raw, 16);
    $key    = hash('sha256', encryptionKey(), true);
    $plain  = openssl_decrypt($cipher, 'AES-256-CBC', $key, OPENSSL_RAW_DATA, $iv);
    return $plain === false ? '' : $plain;
}

/**
 * Store a setting, transparently encrypting secret keys at rest.
 * Empty values are stored empty (which clears the credential).
 */
function setSecretSetting(string $key, string $value): void {
    if ($value !== '' && isSecretSettingKey($key)) {
        $value = encryptSecret($value);
    }
    setSetting($key, $value);
}

/**
 * Massage a settings array for internal consumers: decrypt secret keys so
 * telegram.php, send-mail.php, payments etc. keep working unchanged.
 */
function decryptSettings(array $settings): array {
    foreach (secretSettingKeys() as $k) {
        if (isset($settings[$k])) {
            $settings[$k] = decryptSecret($settings[$k]);
        }
    }
    return $settings;
}

// ─── Month/Folder Helpers ───────────────────────────────────────────────────
function getMonthFolder(string $month, int $year): string {
    $month = strtolower(trim($month));
    return "{$month}_{$year}";
}

function ensureUploadDir(string $subpath): string {
    $dir = UPLOADS_DIR . '/' . ltrim($subpath, '/');
    if (!is_dir($dir)) {
        mkdir($dir, 0755, true);
    }
    return $dir;
}

function getClientIp(): string {
    if (!empty($_SERVER['HTTP_CF_CONNECTING_IP'])) {
        return trim((string)$_SERVER['HTTP_CF_CONNECTING_IP']);
    }
    if (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
        $parts = array_map('trim', explode(',', (string)$_SERVER['HTTP_X_FORWARDED_FOR']));
        if (!empty($parts[0])) {
            return $parts[0];
        }
    }
    return $_SERVER['REMOTE_ADDR'] ?? 'unknown';
}

function ipVersion(string $ip): int {
    return filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) ? 6 : 4;
}

function subnetForIp(string $ip, int $maskV4 = 24, int $maskV6 = 64): string {
    if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
        $bin = inet_pton($ip);
        if ($bin === false) {
            return $ip;
        }
        $maskBytes = intdiv($maskV6, 8);
        $remainder = $maskV6 % 8;
        $masked = substr($bin, 0, $maskBytes);
        if ($remainder > 0) {
            $byte = ord(substr($bin, $maskBytes, 1));
            $byte = $byte & (0xFF << (8 - $remainder));
            $masked .= chr($byte);
            $maskBytes++;
        }
        $masked = str_pad($masked, 16, "\0");
        return inet_ntop($masked) . "/{$maskV6}";
    }

    $octets = explode('.', $ip);
    if (count($octets) !== 4) {
        return $ip;
    }
    return sprintf('%d.%d.%d.0/%d', (int)$octets[0], (int)$octets[1], (int)$octets[2], $maskV4);
}

function ipRangeForSubnet(string $cidr): array {
    if (str_contains($cidr, '/')) {
        [$ip, $prefix] = explode('/', $cidr, 2);
        $prefix = (int)$prefix;
    } else {
        $ip = $cidr;
        $prefix = filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6) ? 64 : 24;
    }

    if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
        $bin = inet_pton($ip);
        if ($bin === false) {
            return [$cidr, $cidr];
        }
        $start = $bin;
        $end = $bin;
        $fullBytes = intdiv($prefix, 8);
        $remainder = $prefix % 8;
        for ($i = $fullBytes; $i < 16; $i++) {
            $start[$i] = "\0";
            $end[$i] = "\xff";
        }
        if ($remainder > 0 && $fullBytes < 16) {
            $mask = 0xFF << (8 - $remainder);
            $start[$fullBytes] = chr(ord($start[$fullBytes]) & $mask);
            $end[$fullBytes] = chr(ord($end[$fullBytes]) | (0xFF ^ $mask));
        }
        return [inet_ntop($start), inet_ntop($end)];
    }

    $long = ip2long($ip);
    if ($long === false) {
        return [$cidr, $cidr];
    }
    $mask = -1 << (32 - $prefix);
    $start = $long & $mask;
    $end = $start | (~$mask & 0xFFFFFFFF);
    return [long2ip($start), long2ip($end)];
}

function normalizeSubnet(string $ip): string {
    return subnetForIp($ip);
}

function getBanForIp(string $ip): ?array {
    global $pdo;
    if (!$pdo) {
        return null;
    }
    $version = ipVersion($ip);
    $stmt = $pdo->prepare(
        "SELECT * FROM ip_bans
         WHERE active = 1
         AND ip_version = ?
         AND ban_start <= ?
         AND ban_end >= ?
         ORDER BY created_at DESC
         LIMIT 1"
    );
    $stmt->execute([$version, $ip, $ip]);
    $ban = $stmt->fetch();
    return $ban ?: null;
}

function queueMail(string $to, string $subject, string $body): void {
    global $pdo;
    if (!$pdo || empty($to)) {
        return;
    }
    $stmt = $pdo->prepare("INSERT INTO mail_queue (id, to_email, subject, body, sent) VALUES (?, ?, ?, ?, 0)");
    $stmt->execute([generateId(), $to, $subject, $body]);
}

function recordIpBan(string $ip, string $reason, string $email = '', int $failedAttempts = 0, string $source = 'admin-login'): ?array {
    global $pdo;
    if (!$pdo) {
        return null;
    }
    $cidr = normalizeSubnet($ip);
    [$banStart, $banEnd] = ipRangeForSubnet($cidr);
    $version = ipVersion($ip);
    $stmt = $pdo->prepare(
        "INSERT INTO ip_bans
            (id, ip_address, ip_version, cidr, ban_start, ban_end, reason, source, email, failed_attempts, active)
         VALUES
            (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1)
         ON DUPLICATE KEY UPDATE
            reason = VALUES(reason),
            source = VALUES(source),
            email = VALUES(email),
            failed_attempts = GREATEST(failed_attempts, VALUES(failed_attempts)),
            active = 1,
            unbanned_at = NULL,
            unbanned_by = NULL"
    );
    $stmt->execute([
        generateId(),
        $ip,
        $version,
        $cidr,
        $banStart,
        $banEnd,
        $reason,
        $source,
        $email,
        $failedAttempts,
    ]);

    $lookup = $pdo->prepare("SELECT * FROM ip_bans WHERE cidr = ? AND active = 1 ORDER BY created_at DESC LIMIT 1");
    $lookup->execute([$cidr]);
    return $lookup->fetch() ?: null;
}

function unbanIpBan(string $id, ?string $adminEmail = null): bool {
    global $pdo;
    if (!$pdo) {
        return false;
    }
    $stmt = $pdo->prepare(
        "UPDATE ip_bans SET active = 0, unbanned_at = NOW(), unbanned_by = ? WHERE id = ?"
    );
    return $stmt->execute([$adminEmail, $id]);
}

// ─── Real MIME detection ────────────────────────────────────────────────────
function detectRealMime(string $filePath, string $fallbackMime = 'application/octet-stream'): string {
    if (function_exists('finfo_open')) {
        $finfo = finfo_open(FILEINFO_MIME_TYPE);
        if ($finfo) {
            $mime = finfo_file($finfo, $filePath);
            finfo_close($finfo);
            return $mime ?: $fallbackMime;
        }
    }
    // finfo not available — fall back to client-supplied MIME or octet-stream
    return $fallbackMime;
}

// ─── Session Security ─────────────────────────────────────────────────────

/**
 * Configure secure session settings.
 * Call BEFORE session_start().
 */
function configureSession(): void {
    $secure = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off');
    $cookieParams = session_get_cookie_params();
    session_set_cookie_params([
        'lifetime' => 0, // until browser closes
        'path'     => $cookieParams['path'] ?? '/',
        'domain'   => $cookieParams['domain'] ?? '',
        'secure'   => $secure,
        'httponly' => true,
        'samesite' => 'Strict',
    ]);

    // Use a project-relative session save path so sessions persist on cPanel
    // (default /tmp may not be writable or may be cleared between requests)
    $sessionDir = __DIR__ . '/../../tmp/sessions';
    if (!is_dir($sessionDir)) {
        @mkdir($sessionDir, 0777, true);
    }
    if (is_dir($sessionDir) && is_writable($sessionDir)) {
        session_save_path($sessionDir);
    }
}

/**
 * Check session idle timeout.
 * Destroys session if more than SESSION_LIFETIME seconds idle.
 * Updates last_activity timestamp on success.
 */
function checkSessionTimeout(int $maxIdleSeconds = 3600): void {
    if (session_status() !== PHP_SESSION_ACTIVE) {
        return;
    }
    $lastActivity = $_SESSION['last_activity'] ?? 0;
    if ($lastActivity > 0 && (time() - $lastActivity) > $maxIdleSeconds) {
        // Session expired — destroy
        $_SESSION = [];
        session_destroy();
        return;
    }
    // Update last activity
    $_SESSION['last_activity'] = time();
}

/**
 * Regenerate session ID to prevent session fixation.
 * Preserves all session data.
 */
function regenerateSession(): void {
    if (session_status() === PHP_SESSION_ACTIVE) {
        session_regenerate_id(true);
    }
}

/**
 * Bind session to client IP and User-Agent.
 * Returns true if the session fingerprint matches.
 */
function validateSessionBinding(): bool {
    if (session_status() !== PHP_SESSION_ACTIVE) {
        return false;
    }
    $ip      = $_SERVER['REMOTE_ADDR'] ?? 'unknown';
    $ua      = $_SERVER['HTTP_USER_AGENT'] ?? '';
    $fingerprint = hash('sha256', $ip . '|' . $ua);

    if (!isset($_SESSION['session_fingerprint'])) {
        // First check — set fingerprint
        $_SESSION['session_fingerprint'] = $fingerprint;
        return true;
    }

    return hash_equals($_SESSION['session_fingerprint'], $fingerprint);
}

/**
 * Full session hardening: configure, start, validate.
 * Call at the start of every admin-protected page.
 * 
 * @param int $maxIdleSeconds Session idle timeout (default 60 min)
 * @return bool True if session is valid
 */
function secureSession(int $maxIdleSeconds = 3600): bool {
    if (session_status() === PHP_SESSION_NONE) {
        configureSession();
        session_start();
    }

    // Check idle timeout
    checkSessionTimeout($maxIdleSeconds);

    // If no admin session, nothing to validate
    if (!isset($_SESSION['admin_id'])) {
        return false;
    }

    // Validate fingerprint binding
    if (!validateSessionBinding()) {
        // Possible hijack — destroy session
        $_SESSION = [];
        session_destroy();
        return false;
    }

    return true;
}

// ─── Real-Time Activity Log & Reactions (idempotent table creation) ─────────
function ensureActivityTables(): void {
    global $pdo;
    if (!$pdo instanceof PDO) return;
    // Run the DDL only once per PHP process. reactions.php is a hot, public
    // endpoint (every visitor click), so we must not fire CREATE TABLE on
    // each request — a static flag keeps it a one-time setup.
    static $checked = false;
    if ($checked) return;
    try {
        $pdo->exec("CREATE TABLE IF NOT EXISTS activity_log (
            id VARCHAR(36) PRIMARY KEY,
            action VARCHAR(50) NOT NULL,
            message TEXT NOT NULL,
            entity_type VARCHAR(50) DEFAULT '',
            entity_id VARCHAR(255) DEFAULT '',
            actor VARCHAR(255) DEFAULT '',
            ip_address VARCHAR(45) DEFAULT '',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_created (created_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
        $pdo->exec("CREATE TABLE IF NOT EXISTS devotional_reaction_votes (
            id INT AUTO_INCREMENT PRIMARY KEY,
            devotional_id VARCHAR(36) NOT NULL,
            emoji VARCHAR(32) NOT NULL,
            ip_hash CHAR(64) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            UNIQUE KEY uk_vote (devotional_id, emoji, ip_hash),
            INDEX idx_devotional (devotional_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4");
    } catch (Throwable $e) {
        // Tables may not exist yet on brand-new installs — install.php creates them.
        return;
    }
    $checked = true;
}

/**
 * Append a real activity entry. Called from admin/devotionals/headers/telegram
 * endpoints so the dashboard's log feed shows genuine, real-time events.
 * Never throws — logging must never break the request that triggered it.
 */
function logActivity(string $action, string $message, string $entityType = '', string $entityId = '', string $actor = ''): void {
    global $pdo;
    if (!$pdo instanceof PDO) return;
    ensureActivityTables();
    if ($actor === '') {
        $actor = trim((string)($_SESSION['admin_name'] ?? '')) !== ''
            ? (string)$_SESSION['admin_name']
            : (string)($_SESSION['admin_email'] ?? '');
    }
    try {
        $stmt = $pdo->prepare(
            "INSERT INTO activity_log (id, action, message, entity_type, entity_id, actor, ip_address)
             VALUES (?, ?, ?, ?, ?, ?, ?)"
        );
        $stmt->execute([
            generateId(),
            substr($action, 0, 50),
            substr($message, 0, 1000),
            substr($entityType, 0, 50),
            substr($entityId, 0, 255),
            $actor,
            getClientIp(),
        ]);
    } catch (Throwable $e) {
        // ignore — logging is best-effort
    }
}

// ─── Parse date parts from "July 20" format ─────────────────────────────────
function parseDateParts(string $dateStr): array {
    $months = [
        'january', 'february', 'march', 'april', 'may', 'june',
        'july', 'august', 'september', 'october', 'november', 'december'
    ];
    $dateStr = trim($dateStr);
    
    // Match "Month Day" pattern
    if (preg_match('/^([A-Za-z]+)\s+(\d+)/i', $dateStr, $m)) {
        return [
            'month' => ucfirst(strtolower($m[1])),
            'day'   => (int)$m[2],
        ];
    }
    
    // Match "Day Month" pattern
    if (preg_match('/^(\d+)\s+([A-Za-z]+)/i', $dateStr, $m)) {
        return [
            'month' => ucfirst(strtolower($m[2])),
            'day'   => (int)$m[1],
        ];
    }
    
    // Fallback: try to find month name
    $lower = strtolower($dateStr);
    foreach ($months as $month) {
        if (strpos($lower, $month) !== false) {
            preg_match('/\d+/', $dateStr, $dm);
            return [
                'month' => ucfirst($month),
                'day'   => isset($dm[0]) ? (int)$dm[0] : 1,
            ];
        }
    }
    
    return ['month' => 'January', 'day' => 1];
}
